const status=document.querySelector('#status');const show=x=>status.textContent=typeof x==='string'?x:JSON.stringify(x,null,2);
const VERSION=chrome.runtime.getManifest().version;
document.querySelector('#title').textContent='ModelPro '+VERSION;
async function activeChat(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const t=tabs[0];if(!t?.id||!String(t.url||'').startsWith('https://chatgpt.com/'))throw new Error('请先打开并选中 chatgpt.com 标签页');return t;}
async function freshChatProbeTab(){const t=await chrome.tabs.create({url:'https://chatgpt.com/',active:false});if(!t?.id)throw new Error('无法创建全新 ChatGPT 探针标签页');if(t.status!=='complete'){await new Promise((resolve,reject)=>{let timer=null;const cleanup=()=>{if(timer)clearTimeout(timer);chrome.tabs.onUpdated.removeListener(onUpdated);};const finish=(error)=>{cleanup();error?reject(error):resolve();};const onUpdated=(tabId,changeInfo,tab)=>{if(tabId!==t.id)return;if(changeInfo.status==='complete'&&String(tab?.url||'').startsWith('https://chatgpt.com/'))finish();};chrome.tabs.onUpdated.addListener(onUpdated);timer=setTimeout(()=>finish(new Error('全新 ChatGPT 页面加载超时')),20000);});}return chrome.tabs.get(t.id);}
async function armFreshProbe(tabId){const [{result}]=await chrome.scripting.executeScript({target:{tabId},func:(id)=>{if(globalThis.__MODELPRO_FRESH_UI_PROBE_ARMED__)return'already-armed';globalThis.__MODELPRO_FRESH_UI_PROBE_ARMED__=true;const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));void(async()=>{const deadline=Date.now()+45000;let stable=0;while(Date.now()<deadline){const trigger=[...document.querySelectorAll('button[aria-haspopup="menu"]')].find((button)=>/选择\s*ChatGPT\s*模型|select\s*chatgpt\s*model/i.test(String(button.getAttribute('aria-label')||'')));const composer=document.querySelector('#prompt-textarea,textarea,[contenteditable="true"],form');if(trigger&&composer){stable+=1;if(stable>=3)break;}else stable=0;await sleep(300);}await sleep(700);try{await chrome.runtime.sendMessage({type:'MODELPRO_UI_COMPAT_PROBE',tabId:id});}catch(error){console.error('[ModelPro probe] fresh-chat runner failed',error);}})();return'armed';},args:[tabId]});return result;}
async function call(message){const r=await chrome.runtime.sendMessage(message);if(!r?.ok)throw new Error(r?.error||'ModelPro 调用失败');return r.data;}
async function exportLog(prefix='ModelPro'){const bundle=await call({type:'GPTLOCK_EXPORT_DIAGNOSTICS',entryLimit:2000});const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ModelPro-v'+VERSION+'-'+(prefix==='ModelPro-auto'?'auto-':'')+new Date().toISOString().replace(/[:.]/g,'-')+'.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return a.download;}
document.querySelector('#probe').onclick=async()=>{try{await chrome.storage.local.set({gptworkEnabledLocal:true});show('正在创建全新 ChatGPT 聊天页。ModelPro 会先在新标签页里等待新版模型按钮和输入区稳定，再自动测试 GPT-5.5 / GPT-5.6 Sol，并自动导出 LOG。即将切换到新标签页，之后无需操作。');const t=await freshChatProbeTab();await armFreshProbe(t.id);show('探针已转交给新标签页后台运行。切换过去后请不要操作，完成时会自动下载 LOG。');await chrome.tabs.update(t.id,{active:true});}catch(e){show('错误：'+e.message);}};
document.querySelector('#start').onclick=async()=>{try{const t=await activeChat();await chrome.storage.local.set({gptworkEnabledLocal:true});show('验证运行中，请保持 ChatGPT 标签页打开。完成后会自动导出 LOG。');const r=await call({type:'GPTLOCK_AUTO_VERIFY',tabId:t.id});show(r);const name=r?.autoVerification?.autoLogDownload?.filename||'后台自动导出的版本化 LOG';show(JSON.stringify(r,null,2)+'\n\n测试已结束，LOG 已自动导出：'+name);}catch(e){show('错误：'+e.message);}};
document.querySelector('#export').onclick=async()=>{try{const name=await exportLog('ModelPro');show('诊断 LOG 已导出：'+name);}catch(e){show('错误：'+e.message);}};