const status=document.querySelector('#status');const show=x=>status.textContent=typeof x==='string'?x:JSON.stringify(x,null,2);
const VERSION=chrome.runtime.getManifest().version;
document.querySelector('#title').textContent='ModelPro '+VERSION;
async function activeChat(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const t=tabs[0];if(!t?.id||!String(t.url||'').startsWith('https://chatgpt.com/'))throw new Error('请先打开并选中 chatgpt.com 标签页');return t;}
async function freshChatProbeTab(){const t=await chrome.tabs.create({url:'https://chatgpt.com/',active:false});if(!t?.id)throw new Error('无法创建全新 ChatGPT 探针标签页');if(t.status!=='complete'){await new Promise((resolve,reject)=>{let timer=null;const cleanup=()=>{if(timer)clearTimeout(timer);chrome.tabs.onUpdated.removeListener(onUpdated);};const finish=(error)=>{cleanup();error?reject(error):resolve();};const onUpdated=(tabId,changeInfo,tab)=>{if(tabId!==t.id)return;if(changeInfo.status==='complete'&&String(tab?.url||'').startsWith('https://chatgpt.com/'))finish();};chrome.tabs.onUpdated.addListener(onUpdated);timer=setTimeout(()=>finish(new Error('全新 ChatGPT 页面加载超时')),20000);});}await new Promise(resolve=>setTimeout(resolve,900));return chrome.tabs.get(t.id);}
async function call(message){const r=await chrome.runtime.sendMessage(message);if(!r?.ok)throw new Error(r?.error||'ModelPro 调用失败');return r.data;}
async function exportLog(prefix='ModelPro'){const bundle=await call({type:'GPTLOCK_EXPORT_DIAGNOSTICS',entryLimit:2000});const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ModelPro-v'+VERSION+'-'+(prefix==='ModelPro-auto'?'auto-':'')+new Date().toISOString().replace(/[:.]/g,'-')+'.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return a.download;}
document.querySelector('#probe').onclick=async()=>{try{await chrome.storage.local.set({gptworkEnabledLocal:true});show('正在自动打开一个全新 ChatGPT 聊天页，然后测试 GPT-5.5 与 GPT-5.6 Sol 的模型菜单发现/选择/当前页面模型识别，并自动导出 LOG。测试期间不要操作新开的 ChatGPT 标签页。');const t=await freshChatProbeTab();const r=await call({type:'MODELPRO_UI_COMPAT_PROBE',tabId:t.id});const name=r?.autoLogDownload?.filename||'后台自动导出的 UI 探针 LOG';show(JSON.stringify(r,null,2)+'\n\n探针已结束，LOG 已自动导出：'+name);}catch(e){show('错误：'+e.message);}};
document.querySelector('#start').onclick=async()=>{try{const t=await activeChat();await chrome.storage.local.set({gptworkEnabledLocal:true});show('验证运行中，请保持 ChatGPT 标签页打开。完成后会自动导出 LOG。');const r=await call({type:'GPTLOCK_AUTO_VERIFY',tabId:t.id});show(r);const name=r?.autoVerification?.autoLogDownload?.filename||'后台自动导出的版本化 LOG';show(JSON.stringify(r,null,2)+'\n\n测试已结束，LOG 已自动导出：'+name);}catch(e){show('错误：'+e.message);}};
document.querySelector('#export').onclick=async()=>{try{const name=await exportLog('ModelPro');show('诊断 LOG 已导出：'+name);}catch(e){show('错误：'+e.message);}};